[package]
name = "ddns-route53"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-route53 = "1"
reqwest = "0.12.7"
tokio = { version = "1", features = ["full"] }
